mex -v CXXFLAGS="\$CXXFLAGS -Wall -pedantic -O3 -std=c++0x"...
    -I../../../eigen/...
    Boonen13.mex.cpp...
    -output Boonen13
    
mex -I../../../eigen/...
    Boonen13.mex.cpp...
    -output Boonen13
    
